### ISSUE TITLE
An assert throws trying to operate on non-installed snap

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1166] opened 2023-01-26 16:49 UTC
![image](https://user-images.githubusercontent.com/105335204/214775111-d722cdc5-ab0a-47b9-be5f-0f6d4367a6e1.png)
Was trying to build a test snap to store the data given by the user in an input field. I connected everything according to the docs. Am I doing something wrong. What does this error mean.

_Originally posted by @kunal-gg in https://github.com/MetaMask/snaps-monorepo/discussions/675#discussioncomment-4784606_
    
From sprint planning on 2023-03-21: This is not a bug. Remove the reporting message.

**Comment by FrederikBolding** [comment] 2023-02-23 12:46
I am not able to reproduce this bug locally. We may need some reproduction steps or it may have been an issue that is already fixed in the latest version of Flask.

**Closed** 2023-03-22 11:10 UTC
Labels: type-bug
