### ISSUE TITLE
Cannot select a range in tx-insights snap UI frame

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-monorepo#1281] opened 2023-03-14 21:19 UTC
Example of the issue: 

https://user-images.githubusercontent.com/19909/225138286-158951e5-a80a-4ef2-a15e-cebb80a971f5.mov

I cannot click and drag to select text in a tx-insights snap UI frame. When highlighting, as soon as I release the left mouse button the highlight goes away. This works fine in dialogs. This is on Google Chrome, MacOS.

**Comment by kenhkan** [comment] 2023-04-04 16:41
To spend half a day researching on whether this is something that we can fix this. If this is not a quick fix, we should close this ticket and let the confirmations UX team handle the long-term fix.

The confirmations UX team is currently rewriting the components that partly cause this issue and may not be an issue in the long-term.

**Comment by david0xd** [comment] 2023-04-20 15:30
I tried to find the cause and fix this. So here is some report that I have.

This bug only exists if multiple (array) of elements are provided to the UI renderer. For example, this issue is not present if one element is used, which can be confirmed by trying the test the insight snap. As displayed on the screenshot below, text can be selected:
![Screenshot 2023-04-20 at 12 53 53](https://user-images.githubusercontent.com/13301024/233412985-205c213a-5768-4289-a788-974b3a19d157.png)

The problem is present when multiple elements are provided to the renderer as documented in the video in this ticket's description. This is happening because of the way how `MetaMaskTemplateRenderer` is working. So, basically the selection of the text is lost when component is re-rendering and re-rendering is happening multiple times in this case (https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/metamask-template-renderer/metamask-template-renderer.js#L42).

**Comment by david0xd** [comment] 2023-04-21 14:32
The main cause of this issue and why `memo` was not working already is because of the keys provided to the elements, which were not deterministic.
Proposed fix is applied in this PR: https://github.com/MetaMask/metamask-extension/pull/18719

**Closed** 2023-04-24 10:56 UTC
