### ISSUE TITLE
onTransaction is called repeatedly 

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#828] opened 2022-10-08 23:04 UTC
When a user selects the snap tabntje onTransaction is not called once but recalled multiple times into infinity

**Comment by FrederikBolding** [comment] 2022-10-10 10:08
My guess would be that the component rerenders more often than we think and our current hook doesn't expect that.

cc @GuillaumeRx

**Comment by GuillaumeRx** [comment] 2022-10-10 10:12
Yes, it seems like one of the parent components updates more often then we thought. This may be due to the transaction logic.

Duplicate of #816

**Comment by ritave** [comment] 2022-10-10 16:46
The call should happen only the first time during the first render and then the data should be cached in the UI

**Comment by FrederikBolding** [comment] 2022-10-14 11:01
> The call should happen only the first time during the first render and then the data should be cached in the UI

Opened a PR that fixes this, but have asked for feedback from the extension team

**Closed** 2022-10-28 08:37 UTC
Labels: bug
